language: go
sudo: false
go:
  - tip
before_install:
  - sudo apt-get install -f -y --force-yes vlc
  - go get github.com/mattn/goveralls
  - go get github.com/Konstantin8105/FreePort
script:
  - $GOPATH/bin/goveralls -service=travis-ci
